# Generated by Django 3.1 on 2020-08-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cid',
            field=models.IntegerField(default=None),
        ),
    ]
