# Generated by Django 3.1 on 2020-08-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name= 'Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length= 255)),
                ('quantity', models.IntegerField()),
                ('totalsale' , models.IntegerField(editable = False, null = True)),
                ('capital_price',models.DecimalField(max_digits=10,decimal_places=2)),
                ('selling_price',models.DecimalField(max_digits=10,decimal_places=2)),
                ('discount', models.DecimalField(max_digits=10,decimal_places=2)),
                ('item_remaining' , models.IntegerField(editable= False, null = True)),
                ('totalprofit' , models.DecimalField(max_digits=10,decimal_places=2,editable = False, null =True)),
            ],
        ),
    ]