# Generated by Django 3.1 on 2020-08-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, default='')),
                ('quantity', models.IntegerField()),
                ('totalsale', models.IntegerField()),
                ('capital_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('totalprofit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
