# Generated by Django 3.1 on 2020-08-14 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_customer_cid'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(default=None, max_length=255)),
                ('quantity', models.IntegerField(default=None)),
                ('status', models.CharField(choices=[('paid', 'paid'), ('due', 'due')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dueamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customer.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Product.product')),
            ],
        ),
    ]
