# Generated by Django 3.1 on 2020-08-13 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        ('customer', '0002_customer_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('paid', 'paid'), ('due', 'due')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dueamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Product.product')),
                ('sold_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customer.customer')),
            ],
        ),
    ]
