# Generated by Django 3.1 on 2020-08-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200813_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
    ]
