# Generated by Django 3.1 on 2020-08-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sales_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='Discount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='sales',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
