# Generated by Django 3.1 on 2020-08-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_sales_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('sold_to', models.CharField(max_length=55)),
                ('item', models.CharField(max_length=55)),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'paid'), ('due', 'due')], max_length=20)),
                ('dueamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
