# Generated by Django 3.1 on 2020-08-16 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_cid'),
        ('Product', '0002_auto_20200815_1818'),
        ('sales', '0006_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Product.product'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sold_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customer.customer'),
        ),
    ]
